// Package export renders a Plan into formats consumable by external
// execution tooling. The initial target is the Safe Transaction Builder
// batch format, which can be imported into the Safe web app for review and
// multisig execution.
package export

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/chainform/chainform/internal/plan"
)

// safeBatch mirrors the Safe Transaction Builder JSON schema (version 1.0).
type safeBatch struct {
	Version      string   `json:"version"`
	ChainID      string   `json:"chainId"`
	CreatedAt    int64    `json:"createdAt"`
	Meta         safeMeta `json:"meta"`
	Transactions []safeTx `json:"transactions"`
}

type safeMeta struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type safeTx struct {
	To    string `json:"to"`
	Value string `json:"value"`
	Data  string `json:"data"`
}

// Safe writes the plan as a Safe Transaction Builder batch. createdAt is a
// Unix-millisecond timestamp supplied by the caller (kept out of this package
// so the output is deterministic and testable).
func Safe(w io.Writer, p *plan.Plan, createdAt int64) error {
	batch := safeBatch{
		Version:   "1.0",
		ChainID:   fmt.Sprintf("%d", p.Chain.ChainID),
		CreatedAt: createdAt,
		Meta: safeMeta{
			Name:        "ChainForm Plan",
			Description: fmt.Sprintf("%d operation(s) generated by ChainForm", len(p.Operations)),
		},
		Transactions: make([]safeTx, 0, len(p.Operations)),
	}

	for _, op := range p.Operations {
		value := "0"
		if op.Value != nil {
			value = op.Value.String()
		}
		batch.Transactions = append(batch.Transactions, safeTx{
			To:    op.To.Hex(),
			Value: value,
			Data:  fmt.Sprintf("0x%x", op.Calldata),
		})
	}

	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(batch)
}
